<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ ucfirst($type) }} Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 9px;
            color: #333;
            margin: 30px;
        }

        .header {
            width: 100%;
            border-bottom: 2px solid #0d6efd;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }

        .logo {
            width: 60px;
            height: 60px;
        }

        .company-name {
            font-size: 24px;
            font-weight: bold;
            color: #0d6efd;
            margin-bottom: 5px;
        }

        .contact {
            font-size: 11px;
            line-height: 1.5;
            color: #666;
        }

        .report-title {
            text-align: center;
            margin: 25px 0 10px;
            font-size: 20px;
            font-weight: bold;
        }

        .report-date {
            text-align: right;
            font-size: 11px;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            /* table-layout:fixed; */
        }

        table th {
            background: #0d6efd;
            color: #fff;
            border: 1px solid #ddd;
            padding: 8px;
            font-size: 9px;
            word-wrap:break-word;
            overflow-wrap:break-word;
        }

        table td {
            border: 1px solid #ddd;
            padding: 5px;
            font-size: 9px;
            word-wrap:break-word;
            overflow-wrap:break-word;
        }

        table tr:nth-child(even) {
            background: #f8f9fa;
        }

        .footer {
            margin-top: 35px;
            text-align: center;
            font-size: 10px;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>

</head>

<body>

    <!-- Header -->

    <table class="header" style="border: none;">
        <tr style="border: none;">

            <td style="border: none; width:80px;">

                @if($setting && $setting->logo)
                    <img src="{{ public_path('storage/'.$setting->logo) }}"
                         class="logo">
                @endif

            </td>

            <td style="border: none;">

                <div class="company-name">
                    {{ $setting->site_name }}
                </div>

                <div class="contact">
                    {!! nl2br(e($setting->contact_information)) !!}
                </div>

            </td>

        </tr>
    </table>

    <!-- Report Title -->

    <div class="report-title">
        {{ ucfirst($type) }} Report
    </div>

    <div class="report-date">
        Generated:
        {{ now()->format('d M Y, h:i A') }}
    </div>

    <!-- Report Table -->

    <table>

        <thead>

            <tr>

                @if($data->count())

                    @foreach(array_keys($data->first()->toArray()) as $column)

                        <th>
                            {{ ucwords(str_replace('_', ' ', $column)) }}
                        </th>

                    @endforeach

                @endif

            </tr>

        </thead>

        <tbody>

            @forelse($data as $row)

                <tr>

                    @foreach($row->toArray() as $value)

                        <td>{{ $value }}</td>

                    @endforeach

                </tr>

            @empty

                <tr>

                    <td colspan="100%" style="text-align:center;">
                        No records found.
                    </td>

                </tr>

            @endforelse

        </tbody>

    </table>

    <!-- Footer -->

    <div class="footer">

        © {{ date('Y') }}
        {{ $setting->site_name }} |
        Generated by {{ $setting->site_name ?? 'BillVexa' }} Admin System

    </div>

</body>

</html>