<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <title>
        {{ ucfirst($type) }} Transactions Report
    </title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 9px;
            color: #333;
            margin: 25px;
        }

        .header {
            width: 100%;
            margin-bottom: 20px;
            border-bottom: 2px solid #0d6efd;
        }

        .logo {
            width: 60px;
            height: 60px;
        }

        .company-name {
            font-size: 22px;
            font-weight: bold;
            color: #0d6efd;
        }

        .contact {
            font-size: 10px;
            color: #666;
        }

        .report-title {
            text-align: center;
            font-size: 18px;
            font-weight: bold;
            margin: 20px 0 5px;
        }

        .report-date {
            text-align: right;
            font-size: 9px;
            margin-bottom: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background: #0d6efd;
            color: white;
            border: 1px solid #ddd;
            padding: 6px;
            font-size: 8px;
        }

        td {
            border: 1px solid #ddd;
            padding: 5px;
            font-size: 8px;
        }

        tr:nth-child(even) {
            background: #f8f9fa;
        }

        .footer {
            margin-top: 25px;
            text-align: center;
            font-size: 9px;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 8px;
        }
    </style>
</head>

<body>

    <table class="header">
        <tr>
            <td style="width:80px; border:none;">

                @if($setting && $setting->logo)
                    <img
                        src="{{ public_path('storage/' . $setting->logo) }}"
                        class="logo"
                    >
                @endif

            </td>

            <td style="border:none;">

                <div class="company-name">
                    {{ $setting->site_name ?? 'BillVexa' }}
                </div>

                <div class="contact">
                    {!! nl2br(e($setting->contact_information ?? '')) !!}
                </div>

            </td>
        </tr>
    </table>

    <div class="report-title">
        {{ ucfirst($type) }} Transactions Report
    </div>

    <div class="report-date">
        Generated:
        {{ now()->format('d M Y, h:i A') }}
    </div>

    <table>

        <thead>
            <tr>

                @if($data->count())

                    @foreach(array_keys($data->first()) as $column)

                        <th>
                            {{ $column }}
                        </th>

                    @endforeach

                @endif

            </tr>
        </thead>

        <tbody>

            @forelse($data as $row)

                <tr>

                    @foreach($row as $value)

                        <td>
                            {{ $value ?? '' }}
                        </td>

                    @endforeach

                </tr>

            @empty

                <tr>
                    <td colspan="20" style="text-align:center;">
                        No transactions found.
                    </td>
                </tr>

            @endforelse

        </tbody>

    </table>

    <div class="footer">

        © {{ date('Y') }}

        {{ $setting->site_name ?? 'BillVexa' }}

        | Generated by
        {{ $setting->site_name ?? 'BillVexa' }} Admin System

    </div>

</body>

</html>